name: komfy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  introduction_screen: ^3.1.17
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  image_path: "assets/images/komfy_logo.png"
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#F4F9FF"
  adaptive_icon_foreground: "assets/images/komfy_logo.png"

flutter_native_splash:
    color: "#00FFFF"
    color_dark: "#00FFFF"
    image: assets/images/komfy_logo.png
    android: true
    ios: true
    android_gravity: center
    ios_content_mode: scaleAspectFit

flutter:
  uses-material-design: true
  assets:
    - assets/images/
