name: komfy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: "^0.14.3"
  onboarding: ^4.0.2
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.0.0
  image_picker: ^1.0.0
  http: ^1.0.0
  cloud_firestore: ^4.17.5
  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  oktoast: ^3.3.1
  table_calendar: ^3.0.9
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  pointycastle: ^3.7.4
  asn1lib: ^1.6.4
  flutter_floating_bottom_bar: ^1.3.0
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  rflutter_alert: ^2.0.7
  url_launcher: ^6.3.1
  fl_chart: ^1.0.0
  google_nav_bar: ^5.0.7
  youtube_player_flutter: ^9.0.4
  cryptography: ^2.7.0
  convert: ^3.1.1
  argon2: ^1.0.1
  flutter_native_splash: ^2.4.6
  basic_utils: ^5.6.2
  shimmer: ^3.0.0
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf
